export const productData = [
  {
    id: 1,
    title: "waffle",
    detail: "Waffle with Berries",
    price: 6.5,
    img: "/images/jonior/product-list/image-waffle-desktop.jpg",
  },
  {
    id: 2,
    title: "creme brulee",
    detail: "Vanilla Bean Crème Brûlée",
    price: 7.0,
    img: "/images/jonior/product-list/image-creme-brulee-desktop.jpg",
  },
  {
    id: 3,
    title: "macaron",
    detail: "Macaron Mix of Five",
    price: 8.0,
    img: "/images/jonior/product-list/image-macaron-desktop.jpg",
  },
  {
    id: 4,
    title: "tiramisu",
    detail: "Classic Tiramisu",
    price: 5.5,
    img: "/images/jonior/product-list/image-tiramisu-desktop.jpg",
  },
  {
    id: 5,
    title: "baklava",
    detail: "Pistachio Baklava",
    price: 4.0,
    img: "/images/jonior/product-list/image-baklava-desktop.jpg",
  },
  {
    id: 6,
    title: "pie",
    detail: "Lemon Meringue Pie",
    price: 5.0,
    img: "/images/jonior/product-list/image-meringue-desktop.jpg",
  },
  {
    id: 7,
    title: "cake",
    detail: "Red Velvet Cake",
    price: 4.5,
    img: "/images/jonior/product-list/image-cake-desktop.jpg",
  },
  {
    id: 8,
    title: "brownie",
    detail: "Salted Caramel Brownie",
    price: 5.5,
    img: "/images/jonior/product-list/image-brownie-desktop.jpg",
  },
  {
    id: 9,
    title: "panna cotta",
    detail: "Vanilla Panna Cotta",
    price: 6.5,
    img: "/images/jonior/product-list/image-panna-cotta-desktop.jpg",
  },
];
